# Generated by Django 3.0.2 on 2020-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, null=True)),
                ('entryTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Not Confirmed.'), ('1', 'Confirmed.')], max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Work Registrations',
                'ordering': ['entryTime'],
            },
        ),
    ]
